---
- name: clone VM
  shell: '{{ prlctl }} clone {{ template }} --name {{ inventory_hostname }}'
  delegate_to: localhost

- name: disable DHCP and remove all IP addresses
  shell: '{{ prlctl }} set {{ inventory_hostname }} --dhcp no --ipdel all'
  delegate_to: localhost

- name: set fixed IP
  shell: '{{ prlctl }} set {{ inventory_hostname }} --ipadd {{ ip }}/{{ cidr_mask }}'
  delegate_to: localhost

- name: start VM
  shell: '{{ prlctl }} start {{ inventory_hostname }}'
  delegate_to: localhost

- name: configure host alias on localhost
  lineinfile:
    dest: /etc/hosts
    regexp: '^({{ ip|replace(".", "\.") }}\s|^[^\s]+\s+{{ inventory_hostname }}\s*$)'
    line: '{{ ip }} {{ inventory_hostname }}'
  delegate_to: localhost
  become: yes

- name: wait for VM
  local_action: wait_for host={{ inventory_hostname }} port=22 connect_timeout=1 state=started 
