---
- name: clone VM
  local_action: shell {{ prlctl }} clone {{ template }} --name {{ inventory_hostname }}
  tags: parallels_clone

- name: disable DHCP and remove all IP addresses
  local_action: shell {{ prlctl }} set {{ inventory_hostname }} --dhcp no --ipdel all
  tags: parallels_clone

- name: set fixed IP
  local_action: shell {{ prlctl }} set {{ inventory_hostname }} --ipadd {{ ip }}/{{ cidr_mask }}
  tags: parallels_clone

- name: start VM
  local_action: shell {{ prlctl }} start {{ inventory_hostname }}
  tags: parallels_clone

- name: wait for VM
  local_action: wait_for host={{ inventory_hostname }} port=22 connect_timeout=1 state=started
  tags: parallels_clone

- name: configure hostname in configuration files
  template:
    src: '{{ item }}.j2'
    dest: '/etc/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - hostname
    - hosts
  notify: set hostname
  become: yes
  tags: parallels_clone
